import { Router } from 'express'; import bcrypt from 'bcrypt'; import jwt from 'jsonwebtoken'; import { randomUUID } from 'crypto'; import fs from 'fs/promises'; import path from 'path'; import { Admin } from '../models/Admin.js'; import { Order } from '../models/Order.js'; import { requireAdmin } from '../middleware/auth.js'
const router = Router(); const statuses = ['pending','confirmed','processing','shipped','delivered','cancelled']; const uploadDir = path.resolve('uploads/customizations')
async function saveDataUrl(data?: string) { if (!data?.startsWith('data:image/')) return undefined; await fs.mkdir(uploadDir,{recursive:true}); const match=data.match(/^data:image\/(png|jpeg);base64,(.+)$/); if(!match) return undefined; const name=`${randomUUID()}.${match[1]==='jpeg'?'jpg':'png'}`; await fs.writeFile(path.join(uploadDir,name),Buffer.from(match[2],'base64')); return `/uploads/customizations/${name}` }
router.post('/orders', async (req,res,next)=>{ try { const {customer,items}=req.body; if(!customer?.fullName||!customer?.phone||!customer?.wilaya||!customer?.communeAddress||!Array.isArray(items)||!items.length) return res.status(400).json({message:'Invalid order'}); const parsed=[]; let total=0; for(const i of items){ if(!i?.name||!Number.isInteger(i.quantity)||i.quantity<1||!Number.isFinite(i.price)||i.price<0) return res.status(400).json({message:'Invalid item'}); const custom=Boolean(i.customized); const c=i.customization||{}; const frontImage=custom?await saveDataUrl(c.frontPreview):undefined; const backImage=custom?await saveDataUrl(c.backPreview):undefined; if(custom&&(!frontImage||!backImage)) return res.status(400).json({message:'Customization previews are required'}); parsed.push({type:custom?'custom_tshirt':'product',productId:i.productId,name:i.name,image:custom?undefined:i.image,frontImage,backImage,customizationData:custom?{front:c.front,back:c.back,color:c.color}:undefined,quantity:i.quantity,unitPrice:i.price,size:i.size,color:i.color}); total+=i.price*i.quantity } const order=await Order.create({customer:{...customer,commune:customer.communeAddress,address:customer.communeAddress},items:parsed,total,status:'pending'}); res.status(201).json({id:order.id,status:order.status}) } catch(e){next(e)} })
router.post('/admin/login', async(req,res,next)=>{try{const {username,password}=req.body;if(!username||!password)return res.status(400).json({message:'Username and password required'});const admin=await Admin.findOne({username});if(!admin||!await bcrypt.compare(password,admin.passwordHash))return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({id:admin.id,username:admin.username},process.env.JWT_SECRET!,{expiresIn:process.env.JWT_EXPIRES_IN||'7d'} as jwt.SignOptions);res.json({token,admin:{id:admin.id,username:admin.username}})}catch(e){next(e)}})
router.get('/admin/orders',requireAdmin,async(_req,res,next)=>{try{const orders=await Order.find().sort({createdAt:-1}).select('customer.fullName customer.phone total status items createdAt');res.json(orders.map(o=>({id:o.id,customerName:o.customer?.fullName||'',phone:o.customer?.phone||'',total:o.total,status:o.status,itemCount:o.items.length,createdAt:o.createdAt})))}catch(e){next(e)}})
router.get('/admin/orders/:id',requireAdmin,async(req,res,next)=>{try{const order=await Order.findById(req.params.id);if(!order)return res.status(404).json({message:'Order not found'});res.json(order)}catch(e){next(e)}})
router.patch('/admin/orders/:id/status',requireAdmin,async(req,res,next)=>{try{if(!statuses.includes(req.body.status))return res.status(400).json({message:'Invalid status'});const order=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!order)return res.status(404).json({message:'Order not found'});res.json(order)}catch(e){next(e)}})
export default router
