import { Router } from 'express'
import bcrypt from 'bcrypt'
import jwt from 'jsonwebtoken'
import { randomUUID } from 'crypto'
import fsSync from 'fs'
import path from 'path'
import multer from 'multer'
import { Admin } from '../models/Admin.js'
import { Order } from '../models/Order.js'
import { Product } from '../models/Product.js'
import { requireAdmin } from '../middleware/auth.js'
import { normalizeCategory, normalizeColor } from '../config/catalog.js'

const router = Router(); const statuses = ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']; const uploadDir = path.resolve('uploads'); fsSync.mkdirSync(path.join(uploadDir, 'products'), { recursive: true }); fsSync.mkdirSync(path.join(uploadDir, 'customizations'), { recursive: true })
const upload = multer({ storage: multer.diskStorage({ destination: (_req, _file, done) => done(null, path.join(uploadDir, 'products')), filename: (_req, file, done) => done(null, `${randomUUID()}${path.extname(file.originalname).toLowerCase()}`) }), limits: { fileSize: 8 * 1024 * 1024 }, fileFilter: (_req, file, done) => done(null, /^image\/(png|jpe?g|webp|gif)$/.test(file.mimetype)) })
const customizationUpload = multer({ storage: multer.diskStorage({ destination: (_req, _file, done) => done(null, path.join(uploadDir, 'customizations')), filename: (_req, file, done) => done(null, `${randomUUID()}${path.extname(file.originalname).toLowerCase() || '.bin'}`) }), limits: { fileSize: 12 * 1024 * 1024 }, fileFilter: (_req, file, done) => done(null, /^image\/(png|jpe?g|webp|gif|svg\+xml)$/.test(file.mimetype)) })
function fileMetadata(file: Express.Multer.File, role: string) { const url = `/uploads/customizations/${file.filename}`; return { role, url, path: url, fileName: file.filename, originalName: file.originalname, mimeType: file.mimetype, size: file.size } }
function publicProduct(product: any) { const value = product.toObject ? product.toObject() : product; return { ...value, id: String(value._id), _id: undefined, price: value.salePrice ?? value.price } }
function normalizeProduct(body: any) { const parse = (v: unknown) => typeof v === 'string' && v.startsWith('[') ? JSON.parse(v) : v; const strings = (v: unknown) => Array.isArray(parse(v)) ? parse(v).map(String).map((x: string) => x.trim()).filter(Boolean) : []; const colors = [...new Set(strings(body.colors).map(normalizeColor).filter(Boolean))] as string[]; const category = normalizeCategory(body.category); const rawVariants = parse(body.variants); const variants = Array.isArray(rawVariants) ? rawVariants.map((v: any) => ({ color: normalizeColor(v.color), size: String(v.size || '').trim(), stock: Math.max(0, Number(v.stock) || 0) })).filter((v: any) => v.color && v.size) : []; return { name: String(body.name || '').trim(), description: String(body.description || '').trim(), price: Number(body.price), salePrice: body.salePrice === '' || body.salePrice === undefined ? undefined : Number(body.salePrice), category, collection: String(body.collection || '').trim(), sizes: strings(body.sizes), colors, variants, stock: Math.max(0, Number(body.stock) || 0), sku: String(body.sku || '').trim() || undefined, active: body.active !== false && body.active !== 'false', label: String(body.label || '').trim(), featured: body.featured === true || body.featured === 'true', newest: body.newest === true || body.newest === 'true', visual: String(body.visual || '').trim() } }

router.get('/products', async (req, res, next) => { try { const products = await Product.find(req.query.includeInactive === 'true' ? {} : { active: true }).sort({ featured: -1, createdAt: -1 }); res.json(products.map(publicProduct)) } catch (e) { next(e) } })
router.get('/products/:id', async (req, res, next) => { try { const p = await Product.findById(req.params.id); if (!p || (!p.active && req.query.includeInactive !== 'true')) return res.status(404).json({ message: 'Produit introuvable' }); res.json(publicProduct(p)) } catch (e) { next(e) } })
router.post('/customizations/upload', customizationUpload.array('files', 12), (req, res) => { const files = (req.files || []) as Express.Multer.File[]; const roles = Array.isArray(req.body.roles) ? req.body.roles : [req.body.roles]; res.status(201).json({ files: files.map((file, index) => fileMetadata(file, String(roles[index] || 'design'))) }) })
router.post('/orders', async (req, res, next) => { try { const { customer, items } = req.body; if (!customer?.fullName || !customer?.phone || !customer?.wilaya || !customer?.communeAddress || !Array.isArray(items) || !items.length) return res.status(400).json({ message: 'Informations de commande incomplètes' }); const parsed: any[] = []; let total = 0; for (const i of items) { if (!i?.name || !Number.isInteger(i.quantity) || i.quantity < 1 || !Number.isFinite(i.price) || i.price < 0) return res.status(400).json({ message: 'Article invalide' }); const custom = Boolean(i.customized), c = i.customization || {}; if (custom && (!c.frontPreview || !c.backPreview)) return res.status(400).json({ message: 'Les aperçus de personnalisation sont requis' }); const p = !custom && i.productId ? await Product.findById(i.productId) : null; const unitPrice = p ? (p.salePrice ?? p.price) : Number(i.price); if (p && p.stock < i.quantity) return res.status(409).json({ message: `Stock insuffisant pour ${p.name}` }); if (p) await Product.updateOne({ _id: p.id }, { $inc: { stock: -i.quantity } }); parsed.push({ type: custom ? 'custom_tshirt' : 'product', productId: i.productId, name: p?.name || i.name, image: custom ? undefined : i.image, frontImage: custom ? c.frontPreview : undefined, backImage: custom ? c.backPreview : undefined, designImage: custom ? c.frontDesignImage : undefined, backDesignImage: custom ? c.backDesignImage : undefined, designFiles: custom ? c.designFiles : undefined, customizationData: custom ? { front: c.front, back: c.back, color: c.color, printArea: c.printArea } : undefined, quantity: i.quantity, unitPrice, size: i.size, color: i.color }); total += unitPrice * i.quantity } const order = await Order.create({ customer: { ...customer, commune: customer.communeAddress, address: customer.communeAddress }, items: parsed, total, status: 'pending' }); res.status(201).json({ id: order.id, status: order.status, total: order.total }) } catch (e) { next(e) } })
router.post('/admin/login', async (req, res, next) => { try { const { username, password } = req.body; if (!username || !password) return res.status(400).json({ message: 'Identifiants requis' }); const a = await Admin.findOne({ username }); if (!a || !await bcrypt.compare(password, a.passwordHash)) return res.status(401).json({ message: 'Identifiants invalides' }); const token = jwt.sign({ id: a.id, username: a.username }, process.env.JWT_SECRET!, { expiresIn: process.env.JWT_EXPIRES_IN || '7d' } as jwt.SignOptions); res.json({ token, admin: { id: a.id, username: a.username } }) } catch (e) { next(e) } })
router.get('/admin/orders', requireAdmin, async (req, res, next) => { try { const filter: any = {}; if (statuses.includes(String(req.query.status))) filter.status = req.query.status; if (req.query.from || req.query.to) filter.createdAt = { ...(req.query.from ? { $gte: new Date(String(req.query.from)) } : {}), ...(req.query.to ? { $lte: new Date(`${req.query.to}T23:59:59.999Z`) } : {}) }; if (req.query.q) { const q = String(req.query.q); filter.$or = [{ 'customer.fullName': new RegExp(q, 'i') }, { 'customer.phone': new RegExp(q, 'i') }]; if (/^[a-f\d]{24}$/i.test(q)) filter.$or.push({ _id: q }) } const orders = await Order.find(filter).sort({ createdAt: -1 }); res.json(orders.map((o: any) => ({ id: o.id, customerName: o.customer?.fullName || '', phone: o.customer?.phone || '', total: o.total, status: o.status, itemCount: o.items.length, createdAt: o.createdAt }))) } catch (e) { next(e) } })
router.get('/admin/dashboard', requireAdmin, async (_req, res, next) => { try { const orders = await Order.find().sort({ createdAt: -1 }); const count = (s: string) => orders.filter((o: any) => o.status === s).length; const kept = orders.filter((o: any) => o.status !== 'cancelled'); const products = new Map<string, any>(); orders.forEach((o: any) => o.items.forEach((i: any) => { const v = products.get(i.name) || { name: i.name, quantity: 0 }; v.quantity += i.quantity; products.set(i.name, v) })); res.json({ metrics: { revenue: kept.reduce((s: number, o: any) => s + o.total, 0), totalOrders: orders.length, averageOrder: kept.length ? kept.reduce((s: number, o: any) => s + o.total, 0) / kept.length : 0, pending: count('pending'), confirmed: count('confirmed'), processing: count('processing'), shipped: count('shipped'), delivered: count('delivered'), cancelled: count('cancelled') }, recentOrders: orders.slice(0, 8).map((o: any) => ({ id: o.id, customerName: o.customer.fullName, total: o.total, status: o.status, itemCount: o.items.length, createdAt: o.createdAt })), topProducts: [...products.values()].sort((a, b) => b.quantity - a.quantity).slice(0, 5) }) } catch (e) { next(e) } })
router.get('/admin/orders/:id', requireAdmin, async (req, res, next) => { try { const o = await Order.findById(req.params.id); if (!o) return res.status(404).json({ message: 'Commande introuvable' }); res.json(o) } catch (e) { next(e) } })
router.patch('/admin/orders/:id/status', requireAdmin, async (req, res, next) => { try { if (!statuses.includes(req.body.status)) return res.status(400).json({ message: 'Statut invalide' }); const o = await Order.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true }); if (!o) return res.status(404).json({ message: 'Commande introuvable' }); res.json(o) } catch (e) { next(e) } })
router.get('/admin/products', requireAdmin, async (_req, res, next) => { try { res.json((await Product.find().sort({ createdAt: -1 })).map(publicProduct)) } catch (e) { next(e) } })
async function saveProduct(req: any, res: any, next: any, id?: string) { try { const data = normalizeProduct(req.body); if (!data.name || !data.category || !Number.isFinite(data.price) || data.price < 0) return res.status(400).json({ message: 'Nom, catégorie et prix valide requis' }); const uploads = ((req.files || []) as Express.Multer.File[]).map(f => `/uploads/products/${f.filename}`); const existing = req.body.existingImages ? JSON.parse(req.body.existingImages) : []; const dataWithImages: any = { ...data, images: [...existing, ...uploads] }; const p = id ? await Product.findByIdAndUpdate(id, dataWithImages, { new: true, runValidators: true }) : await Product.create(dataWithImages); if (!p) return res.status(404).json({ message: 'Produit introuvable' }); res.status(id ? 200 : 201).json(publicProduct(p)) } catch (e) { next(e) } }
router.post('/admin/products', requireAdmin, upload.array('images', 8), (req, res, next) => saveProduct(req, res, next))
router.patch('/admin/products/:id', requireAdmin, upload.array('images', 8), (req, res, next) => saveProduct(req, res, next, String(req.params.id)))
router.delete('/admin/products/:id', requireAdmin, async (req, res, next) => { try { const p = await Product.findByIdAndDelete(req.params.id); if (!p) return res.status(404).json({ message: 'Produit introuvable' }); res.status(204).end() } catch (e) { next(e) } })
export default router
