import { useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { api } from '../lib/api'
import { AdminNav } from '../components/AdminNav'
const statuses = ['', 'pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled']; const money = value => `${Number(value || 0).toLocaleString('fr-FR')} DA`
export function AdminDashboardPage() {
  const token = localStorage.getItem('alchemist-admin-token'); const [dashboard, setDashboard] = useState(null); const [orders, setOrders] = useState([]); const [filters, setFilters] = useState({ status: '', q: '', from: '', to: '' }); const [error, setError] = useState('')
  useEffect(() => { if (token) api('/admin/dashboard').then(setDashboard).catch(e => setError(e.message)) }, [token])
  useEffect(() => { if (!token) return; const params = new URLSearchParams(Object.entries(filters).filter(([, v]) => v)); api(`/admin/orders?${params}`).then(setOrders).catch(e => setError(e.message)) }, [token, filters])
  if (!token) return <Navigate to="/admin/login" replace />
  const m = dashboard?.metrics
  return <main className="admin-shell"><AdminNav /><header className="admin-header"><div><p className="eyebrow">Gestion de boutique</p><h1>Dashboard.</h1></div><Link className="button button-dark" to="/admin/products/new">Ajouter un produit</Link></header>{error && <p className="form-error">{error}</p>}{!dashboard ? <p className="admin-message">Chargement du back-office…</p> : <><section className="metric-grid">{[['Chiffre d’affaires', money(m.revenue)], ['Commandes', m.totalOrders], ['Panier moyen', money(m.averageOrder)], ['En attente', m.pending], ['Confirmées', m.confirmed], ['En préparation', m.processing], ['Expédiées / livrées', m.shipped + m.delivered], ['Annulées', m.cancelled]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><div className="dashboard-lower"><section className="admin-panel"><p className="eyebrow">Produits les plus commandés</p>{dashboard.topProducts.length ? dashboard.topProducts.map(p => <p className="rank" key={p.name}><b>{p.name}</b><span>{p.quantity} unités</span></p>) : <p>Aucune donnée de vente.</p>}</section><section className="admin-panel"><p className="eyebrow">Alertes</p><p>{m.pending ? `${m.pending} commande(s) attend(ent) une confirmation.` : 'Aucune commande en attente.'}</p><p>{m.cancelled ? `${m.cancelled} commande(s) annulée(s) à suivre.` : 'Aucune annulation enregistrée.'}</p></section></div></>}<section className="admin-orders-section"><div className="section-heading"><div><p className="eyebrow">Commandes</p><h2>Toutes les commandes.</h2></div></div><div className="admin-filters"><input value={filters.q} onChange={e => setFilters(f => ({ ...f, q: e.target.value }))} placeholder="Nom, téléphone ou numéro" /><select value={filters.status} onChange={e => setFilters(f => ({ ...f, status: e.target.value }))}>{statuses.map(s => <option key={s} value={s}>{s || 'Tous les statuts'}</option>)}</select><input type="date" value={filters.from} onChange={e => setFilters(f => ({ ...f, from: e.target.value }))} /><input type="date" value={filters.to} onChange={e => setFilters(f => ({ ...f, to: e.target.value }))} /></div><div className="admin-orders">{orders.map(order => <Link className="admin-order-row" to={`/admin/orders/${order.id}`} key={order.id}><div><strong>#{order.id.slice(-8)} · {order.customerName}</strong><span>{new Date(order.createdAt).toLocaleString('fr-FR')}</span></div><span>{order.itemCount} article(s)</span><strong>{money(order.total)}</strong><b className={`status status-${order.status}`}>{order.status}</b></Link>)}{!orders.length && <p className="admin-message">Aucune commande ne correspond aux filtres.</p>}</div></section></main>
}
