import { useEffect, useMemo, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { api, assetUrl } from '../lib/api'
import { useToast } from '../context/useToast'
import { AdminNav } from '../components/AdminNav'

export function AdminProductsPage() {
  const token = localStorage.getItem('alchemist-admin-token'); const { notify } = useToast(); const [products, setProducts] = useState([]); const [q, setQ] = useState(''); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState([]); const [page, setPage] = useState(1)
  const load = () => api('/admin/products').then(setProducts).catch(e => notify(e.message, 'error')).finally(() => setLoading(false)); useEffect(() => { if (token) load() }, [token])
  if (!token) return <Navigate to="/admin/login" replace />
  const remove = async (product) => { if (!window.confirm(`Supprimer « ${product.name} » ?`)) return; try { await api(`/admin/products/${product.id}`, { method: 'DELETE' }); setProducts(v => v.filter(x => x.id !== product.id)); setSelected(v => v.filter(id => id !== product.id)); notify('Produit supprimé.') } catch (e) { notify(e.message, 'error') } }
  const removeSelected = async () => { if (!selected.length || !window.confirm(`Supprimer ${selected.length} produit(s) sélectionné(s) ?`)) return; try { await Promise.all(selected.map((id) => api(`/admin/products/${id}`, { method: 'DELETE' }))); setProducts(v => v.filter(x => !selected.includes(x.id))); setSelected([]); notify('Produits supprimés.') } catch (e) { notify(e.message, 'error') } }
  const shown = products.filter(p => `${p.name} ${p.sku || ''} ${p.category}`.toLowerCase().includes(q.toLowerCase()))
  const pageSize = 9; const pageCount = Math.max(1, Math.ceil(shown.length / pageSize)); const visible = useMemo(() => shown.slice((page - 1) * pageSize, page * pageSize), [shown, page])
  const visibleIds = visible.map((product) => product.id); const allVisibleSelected = visibleIds.length > 0 && visibleIds.every((id) => selected.includes(id))
  const toggleAll = () => setSelected((current) => allVisibleSelected ? current.filter((id) => !visibleIds.includes(id)) : [...new Set([...current, ...visibleIds])])
  return <main className="admin-shell"><AdminNav /><header className="admin-header"><div><p className="eyebrow">Catalogue</p><h1>Produits.</h1></div><Link className="button button-dark" to="/admin/products/new">Ajouter un produit</Link></header><div className="admin-product-toolbar"><input className="admin-search" value={q} onChange={e => { setQ(e.target.value); setPage(1) }} placeholder="Rechercher par nom, catégorie ou SKU" /><label><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll} /> Tout sélectionner</label>{selected.length > 0 && <button className="button button-dark" type="button" onClick={removeSelected}>Supprimer la sélection ({selected.length})</button>}</div>{loading ? <p className="admin-message">Chargement…</p> : <div className="admin-products">{visible.map(p => <article key={p.id} className={`admin-product-row ${selected.includes(p.id) ? 'selected' : ''}`}><input type="checkbox" checked={selected.includes(p.id)} onChange={() => setSelected((current) => current.includes(p.id) ? current.filter(id => id !== p.id) : [...current, p.id])} aria-label={`Sélectionner ${p.name}`} /><img src={assetUrl(p.images?.[0])} alt="" /><div><strong>{p.name}</strong><span>{p.category} · {p.sku || 'Sans SKU'}</span></div><div><strong>{p.price.toLocaleString('fr-FR')} DA</strong><span>Stock : {p.stock}</span></div><b className={`status ${p.active ? '' : 'status-cancelled'}`}>{p.active ? 'actif' : 'inactif'}</b><div className="admin-row-actions"><Link to={`/admin/products/${p.id}/edit`}>Modifier</Link><button type="button" onClick={() => remove(p)}>Supprimer</button></div></article>)}{!visible.length && <p className="admin-message">Aucun produit trouvé.</p>}{pageCount > 1 && <nav className="admin-pagination" aria-label="Pagination des produits"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>← Précédente</button><span>Page {page} / {pageCount}</span><button type="button" disabled={page === pageCount} onClick={() => setPage((value) => value + 1)}>Suivante →</button></nav>}</div>}</main>
}
