import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useCart } from '../context/useCart'
import { assetUrl } from '../lib/api'

export function CartPage() {
  const { items, subtotal, updateQuantity, removeItem, clearCart } = useCart()
  const navigate = useNavigate()
  const [preview, setPreview] = useState(null)
  return <section className="page-section cart-page">
    <div className="page-intro"><p className="eyebrow">Votre sélection</p><h1>Panier</h1><p>{items.length ? `${items.length} article${items.length > 1 ? 's' : ''}` : 'Votre panier est vide.'}</p></div>
    {items.length ? <div className="cart-layout"><div className="cart-list">{items.map((item) => <div className={`cart-line ${item.customized ? 'cart-line-custom' : ''}`} key={item.id}>
      <div className="cart-line-visual">{item.customized && item.customization?.frontPreview ? <div className="custom-previews"><figure><button type="button" onClick={() => setPreview({ item, side: 'front' })}><img src={assetUrl(item.customization.frontPreview)} alt={`${item.name} aperçu face`} /></button><figcaption>Face · Agrandir</figcaption></figure><figure><button type="button" onClick={() => setPreview({ item, side: 'back' })}><img src={assetUrl(item.customization.backPreview || item.customization.frontPreview)} alt={`${item.name} aperçu dos`} /></button><figcaption>Dos · Agrandir</figcaption></figure></div> : item.image ? <img src={assetUrl(item.image)} alt={item.name} /> : <span className={`product-image-${item.visual}`} />}</div>
      <div><p className="product-category">{item.customized ? 'T-shirt personnalisé' : `${item.color || ''} · ${item.size || ''}`}</p><h3>{item.name}</h3>{item.customized ? <div className="custom-cart-details"><small className="custom-badge">Personnalisation unique · face et dos</small><span>Couleur : {item.color}</span><span>Taille : {item.size}</span>{item.customization?.frontDesignImage || item.customization?.backDesignImage ? <span>Design ajouté sur le t-shirt</span> : <span>Mockup enregistré</span>}</div> : null}<button className="cart-remove" type="button" onClick={() => removeItem(item.id)}>Supprimer</button></div>
      <div className="quantity-row"><button type="button" aria-label="Diminuer la quantité" onClick={() => updateQuantity(item.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button type="button" aria-label="Augmenter la quantité" onClick={() => updateQuantity(item.id, item.quantity + 1)}>+</button></div><strong>{(item.price * item.quantity).toLocaleString('fr-FR')} DA</strong>
    </div>)}<button className="cart-clear" type="button" onClick={clearCart}>Vider le panier</button></div><aside className="cart-summary"><p className="eyebrow">Résumé</p><div><span>Sous-total</span><strong>{subtotal.toLocaleString('fr-FR')} DA</strong></div><p>La livraison et le paiement seront confirmés lors de la commande.</p><button className="button button-dark" type="button" onClick={() => navigate('/checkout')}>Passer la commande <span>→</span></button></aside></div> : <div className="empty-state"><h2>Votre panier est vide.</h2><p>Découvrez les pièces de la boutique et ajoutez vos favorites.</p><Link className="button button-dark" to="/shop">Découvrir la boutique</Link></div>}
  {preview && <div className="preview-lightbox" role="dialog" aria-modal="true" aria-label="Aperçu du t-shirt personnalisé" onClick={() => setPreview(null)}><div className="preview-dialog" onClick={event => event.stopPropagation()}><button className="preview-close" type="button" onClick={() => setPreview(null)}>×</button><div className="preview-tabs"><button type="button" className={preview.side === 'front' ? 'active' : ''} onClick={() => setPreview(v => ({ ...v, side: 'front' }))}>FRONT</button><button type="button" className={preview.side === 'back' ? 'active' : ''} onClick={() => setPreview(v => ({ ...v, side: 'back' }))}>BACK</button></div><img src={assetUrl(preview.side === 'front' ? preview.item.customization.frontPreview : preview.item.customization.backPreview || preview.item.customization.frontPreview)} alt={`Aperçu ${preview.side}`} /></div></div>}</section>
}
