import { Link } from 'react-router-dom'
import { collections, products, store } from '../data/store'
import { ProductCard } from '../components/ProductCard'

export function HomePage() {
  return (
    <main id="top">
      <section className="hero">
        <div className="hero-copy"><p className="eyebrow">Boutique de vêtements · Mostaganem</p><h1>Le style de tous les jours, avec une vraie présence.</h1><p className="hero-description">Découvrez une sélection de vêtements et d&apos;accessoires pensés pour exprimer votre style, simplement.</p><Link className="button button-dark" to="/shop">Découvrir la boutique <span>→</span></Link><div className="hero-meta"><span>{store.rating}</span><span>{store.reviewCount} avis Google</span><span>Mostaganem, Algérie</span></div></div>
        <div className="hero-visual"><img src={products[1].images?.[0]} alt="Sweat Studio écru porté" /><div className="hero-sticker">The<br />Alchemist<br />Store</div><p className="hero-caption">Sélection actuelle <span>01 / 06</span></p></div>
      </section>
      <div className="marquee" aria-label="Message de la boutique"><span>THE ALCHEMIST STORE&nbsp; — &nbsp;NEW DROP&nbsp; — &nbsp;MOSTAGANEM&nbsp; — &nbsp;STYLE YOUR WAY&nbsp; — &nbsp;</span><span>THE ALCHEMIST STORE&nbsp; — &nbsp;NEW DROP&nbsp; — &nbsp;MOSTAGANEM&nbsp; — &nbsp;STYLE YOUR WAY&nbsp; — &nbsp;</span></div>
      <section className="featured section"><div className="section-heading"><div><p className="eyebrow">La sélection</p><h2>Pièces choisies pour vous.</h2></div><Link to="/shop" className="text-link">Voir toute la boutique <span>→</span></Link></div><div className="featured-layout"><ProductCard product={products[0]} featured /><div className="featured-side"><ProductCard product={products[1]} /><ProductCard product={products[2]} /></div></div></section>
      <section className="editorial-banner section"><div className="editorial-visual"><span className="editorial-circle" /><span className="editorial-garment" /><span className="editorial-note">New<br />season</span></div><div className="editorial-copy"><p className="eyebrow">La sélection du moment</p><h2>Une garde-robe qui vous ressemble.</h2><p>Des essentiels à porter souvent, des silhouettes à faire évoluer, et des pièces qui trouvent naturellement leur place dans votre quotidien.</p><Link className="text-link" to="/shop?sort=newest">Voir les nouveautés <span>→</span></Link></div></section>
      <section className="collections section" id="collections"><div className="section-heading"><div><p className="eyebrow">Collections</p><h2>Trouvez votre rythme.</h2></div><Link to="/collections" className="text-link">Toutes les collections <span>→</span></Link></div><div className="collection-grid">{collections.slice(0, 3).map((collection, index) => <Link to={`/collections/${collection.id}`} className={`collection-feature collection-feature-${collection.visual}`} key={collection.id}><div className="collection-art" style={{ backgroundImage: `url(${collection.image})` }}><span className={`collection-shape collection-shape-${index + 1}`} /></div><div className="collection-content"><p className="eyebrow">{collection.eyebrow}</p><h3>{collection.name}</h3><span className="text-link">Découvrir <span>→</span></span></div></Link>)}</div></section>
      <section className="visit section" id="about"><div className="visit-copy"><p className="eyebrow">Nous trouver</p><h2>Passez nous voir à Mostaganem.</h2><p>Retrouvez The Alchemist Store au cœur de Mostaganem pour découvrir la sélection en personne.</p><div className="visit-details"><div><span>Adresse</span><strong>{store.address}</strong></div><div><span>Plus Code</span><strong>{store.plusCode}</strong></div><div><span>Horaires</span><strong>{store.openingStatus}</strong></div></div><Link className="button button-outline" to="/contact">Voir les informations <span>→</span></Link></div><div className="map-placeholder"><div className="map-grid" /><div className="map-pin"><span>⌖</span><small>The Alchemist Store</small></div><span className="map-label map-label-one">Mostaganem</span><span className="map-label map-label-two">W3HP+66</span></div></section>
      <section className="social section" id="contact"><div><p className="eyebrow">Suivez-nous</p><h2>Le quotidien, vu par<br /><em>The Alchemist Store.</em></h2></div><div className="social-action"><p>Retrouvez les nouveautés, les pièces disponibles et la vie de la boutique sur Instagram.</p><a className="text-link" href={store.instagram} target="_blank" rel="noreferrer">Voir Instagram <span>↗</span></a></div></section>
    </main>
  )
}
